# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wonda < Formula
  desc "AI-powered content generation CLI"
  homepage "https://wonda.sh"
  version "1.47.0"
  license "Proprietary"

  depends_on "node"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/degausai/wonda/releases/download/v1.47.0/wonda_1.47.0_darwin_amd64.tar.gz"
      sha256 "3044fb2361ac057c3125477f0b302024c6e33781294139b879892a58e3e912f6"

      define_method(:install) do
        bin.install "wonda"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/degausai/wonda/releases/download/v1.47.0/wonda_1.47.0_darwin_arm64.tar.gz"
      sha256 "33af9a722707e8131baffd6a5a33c30a936e7d3440a6b6980ec488a1cdd61a0c"

      define_method(:install) do
        bin.install "wonda"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/degausai/wonda/releases/download/v1.47.0/wonda_1.47.0_linux_amd64.tar.gz"
      sha256 "600227be88c2bb6bc121218c87a43de2c8db6b7bf3e69f927f31f32519aba194"
      define_method(:install) do
        bin.install "wonda"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/degausai/wonda/releases/download/v1.47.0/wonda_1.47.0_linux_arm64.tar.gz"
      sha256 "2dd238e204eb522f8639a5a56dfc516e14b68e9dcad19a4dd3e0a8fb4f77fcb2"
      define_method(:install) do
        bin.install "wonda"
      end
    end
  end

  def post_install
    wonda_bin = Pathname.new(Dir.home)/".wonda"/"bin"/"wonda"
    if wonda_bin.exist?
      opoo "Found a previous shell-installed wonda at #{wonda_bin} — removing it"
      wonda_bin.unlink
      opoo "Your shell config may still have a PATH entry for ~/.wonda/bin."
      opoo "Remove the '# wonda' block from your shell config to avoid conflicts."
    end
  end

  def caveats
    <<~EOS
      If you previously installed wonda via the shell installer or npm,
      the Homebrew version may conflict. Remove other installs:

        rm -rf ~/.wonda/bin/wonda
        npm uninstall -g @degausai/wonda
    EOS
  end

  test do
    system "#{bin}/wonda", "--version"
  end
end
