# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wonda < Formula
  desc "AI-powered content generation CLI"
  homepage "https://wonda.sh"
  version "1.55.0"
  license "Proprietary"

  depends_on "node"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/degausai/wonda/releases/download/v1.55.0/wonda_1.55.0_darwin_amd64.tar.gz"
      sha256 "2b8f39407ec81394ba590293d5dc643cb071392be9d45c8aba696a711af86379"

      define_method(:install) do
        bin.install "wonda"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/degausai/wonda/releases/download/v1.55.0/wonda_1.55.0_darwin_arm64.tar.gz"
      sha256 "93916479f443971bac6ecf9820789f28c668b140ec2e8df40063d7719d51126a"

      define_method(:install) do
        bin.install "wonda"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/degausai/wonda/releases/download/v1.55.0/wonda_1.55.0_linux_amd64.tar.gz"
      sha256 "0116844357bfadba77689428a48d09625542c2b465a2ecb68d96985fcfd47b1f"
      define_method(:install) do
        bin.install "wonda"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/degausai/wonda/releases/download/v1.55.0/wonda_1.55.0_linux_arm64.tar.gz"
      sha256 "3a8ca7e952d2310db52a70bc1af279053da29cdadea4e79c00739472f387b5ff"
      define_method(:install) do
        bin.install "wonda"
      end
    end
  end

  def post_install
    wonda_bin = Pathname.new(Dir.home)/".wonda"/"bin"/"wonda"
    if wonda_bin.exist?
      opoo "Found a previous shell-installed wonda at #{wonda_bin} — removing it"
      wonda_bin.unlink
      opoo "Your shell config may still have a PATH entry for ~/.wonda/bin."
      opoo "Remove the '# wonda' block from your shell config to avoid conflicts."
    end
  end

  def caveats
    <<~EOS
      If you previously installed wonda via the shell installer or npm,
      remove it first so the Homebrew binary is the wonda on your PATH:

        rm -rf ~/.wonda/bin/wonda
        npm uninstall -g @degausai/wonda

      Then, on macOS or Windows, you can run wonda as an always-on
      background relay (starts at login, keeps itself running) by enabling it
      once (not applicable on Linux):

        wonda relay install

      Turn it off any time with:

        wonda relay uninstall
    EOS
  end

  test do
    system "#{bin}/wonda", "--version"
  end
end
