# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wonda < Formula
  desc "AI-powered content generation CLI"
  homepage "https://wonda.sh"
  version "1.63.0"
  license "Proprietary"

  depends_on "node"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/degausai/wonda/releases/download/v1.63.0/wonda_1.63.0_darwin_amd64.tar.gz"
      sha256 "34c3778c93c1346042b2113fc31f8a8646f2915ef5f96793b801b55613a4ea81"

      define_method(:install) do
        bin.install "wonda"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/degausai/wonda/releases/download/v1.63.0/wonda_1.63.0_darwin_arm64.tar.gz"
      sha256 "5965c34705ef685214cc9159d368c019040f6e5716efe410207119a5d8919b00"

      define_method(:install) do
        bin.install "wonda"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/degausai/wonda/releases/download/v1.63.0/wonda_1.63.0_linux_amd64.tar.gz"
      sha256 "3bd88e693a8f87a9a54f00a93665e4f263a77b020e9539d722b29078fb7c3b43"
      define_method(:install) do
        bin.install "wonda"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/degausai/wonda/releases/download/v1.63.0/wonda_1.63.0_linux_arm64.tar.gz"
      sha256 "c8e04ca682e199659e2fe367c4f212d86840d9602590b38ee750ef68764933f1"
      define_method(:install) do
        bin.install "wonda"
      end
    end
  end

  def post_install
    wonda_bin = Pathname.new(Dir.home)/".wonda"/"bin"/"wonda"
    if wonda_bin.exist?
      opoo "Found a previous shell-installed wonda at #{wonda_bin} — removing it"
      wonda_bin.unlink
      opoo "Your shell config may still have a PATH entry for ~/.wonda/bin."
      opoo "Remove the '# wonda' block from your shell config to avoid conflicts."
    end
  end

  def caveats
    <<~EOS
      This formula is the CLI only, by design (Homebrew formulae do not
      install apps). For the full Wonda experience with zero extra steps,
      the recommended installs are the cask (macOS) or winget (Windows):

        brew install --cask degausai/tap/wonda-app

      Already have this CLI? Add the desktop app (menu bar icon, always-on
      relay, opens at login) with one command:

        wonda app install

      Turn everything off (and stay off across logins) with:

        wonda app quit

      Clean removal order: `wonda app quit` first, then
      `brew uninstall wonda`, so nothing is left trying to
      start at login.

      If you previously installed wonda via the shell installer or npm,
      remove the other copy so the Homebrew binary is the wonda on your PATH:

        rm -rf ~/.wonda/bin/wonda
        npm uninstall -g @degausai/wonda
    EOS
  end

  test do
    system "#{bin}/wonda", "--version"
  end
end
